/**
 * Templates nativos/padrão do sistema.
 * São auto-semeados para cada ministério na primeira vez que acessar a página de certificados.
 * A imagem de fundo é referenciada como caminho público (/img/...) para não inflar o banco com base64.
 */

export const CERTIFICADOS_TEMPLATES_PADRAO = [
  {
    id: 'apresentacao-criancas-padrao',
    nome: 'Apresentação de Crianças',
    chave: 'apresentacao-criancas-padrao',
    categoria: 'apresentacao-criancas' as const,
    ativo: true,
    backgroundUrl: '/img/cert_apcrianca.png',
    elementos: [
      {
        x: 135,
        y: 233,
        id: 'aeda01e2-838d-4d69-9f7c-9195b42d765a',
        cor: '#111827',
        tipo: 'texto' as const,
        fonte: 'Comic Sans MS',
        texto: '{crianca_nome}',
        altura: 40,
        largura: 546,
        visivel: true,
        fontSize: 18,
        alinhamento: 'center' as const,
      },
      {
        x: 206,
        y: 310,
        id: '17762201527499ywqz9y',
        cor: '#111827',
        tipo: 'texto' as const,
        fonte: 'Comic Sans MS',
        texto: 'DATA: {data_apresentacao}',
        altura: 29,
        locked: false,
        largura: 376,
        visivel: true,
        fontSize: 14,
        alinhamento: 'center' as const,
      },
      {
        x: 225,
        y: 353,
        id: '1776220095713x4h0m30',
        cor: '#111827',
        tipo: 'texto' as const,
        fonte: 'Comic Sans MS',
        texto: '{pai_nome}',
        altura: 29,
        locked: false,
        largura: 376,
        visivel: true,
        fontSize: 14,
        alinhamento: 'center' as const,
      },
      {
        x: 227,
        y: 384,
        id: '1776220114545jlxw06y',
        cor: '#111827',
        tipo: 'texto' as const,
        fonte: 'Comic Sans MS',
        texto: '{mae_nome}',
        altura: 29,
        locked: false,
        largura: 376,
        visivel: true,
        fontSize: 14,
        alinhamento: 'center' as const,
      },
      {
        x: 55,
        y: 412,
        id: '0d12479c-c9b0-4adf-8f0c-d293dfabc67b',
        cor: '#111827',
        tipo: 'logo' as const,
        fonte: 'Arial',
        altura: 134,
        largura: 115,
        visivel: true,
        fontSize: 16,
        alinhamento: 'left' as const,
      },
      {
        x: 257,
        y: 521,
        id: '5956da07-5f2c-4019-8a14-01bdfe27ac0e',
        cor: '#111827',
        tipo: 'texto' as const,
        fonte: 'Georgia',
        texto: '{nome_igreja}',
        altura: 40,
        largura: 320,
        visivel: true,
        fontSize: 12,
        alinhamento: 'center' as const,
      },
    ],
  },
];
