/**
 * Templates nativos/padrão do sistema.
 * São auto-semeados para cada ministério na primeira vez que acessar a página de certificados.
 * A imagem de fundo é referenciada como caminho público (/img/...) para não inflar o banco com base64.
 */

export const CERTIFICADOS_TEMPLATES_PADRAO = [
  {
    id: 'ministerial-pastor-padrao',
    nome: 'Consagração Pastor(a)',
    chave: 'ministerial-pastor-padrao',
    categoria: 'ministerial' as const,
    ativo: true,
    backgroundUrl: '/img/cert_pastor.jpg',
    elementos: [
      {
        id: 'd72efd08-445f-4778-aa63-cbc3e8a617b5',
        tipo: 'logo' as const,
        x: 61,
        y: 185,
        largura: 90,
        altura: 90,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: '0437f23f-6dfd-4c00-8657-e2515c61b37b',
        tipo: 'texto' as const,
        x: 192,
        y: 222,
        largura: 454,
        altura: 41,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{ministro_nome}',
      },
      {
        id: 'e7d5f046-21f2-4556-bec9-0a65cc0936dd',
        tipo: 'texto' as const,
        x: 217,
        y: 510,
        largura: 199,
        altura: 22,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'right' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '177705368462948dhz32',
        tipo: 'texto' as const,
        x: 421,
        y: 511,
        largura: 199,
        altura: 22,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'left' as const,
        visivel: true,
        texto: '{data_consagracao}',
      },
    ],
  },
  {
    id: 'ministerial-evangelista-padrao',
    nome: 'Consagração Evangelista',
    chave: 'ministerial-evangelista-padrao',
    categoria: 'ministerial' as const,
    ativo: true,
    backgroundUrl: '/img/cert_evangelista.jpg',
    elementos: [
      {
        id: 'ea7378a8-958b-43d3-afdb-b382080cfedc',
        tipo: 'logo' as const,
        x: 54,
        y: 224,
        largura: 94,
        altura: 116,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: '8f382add-8fcb-4bcf-9dd3-524e74caa5a4',
        tipo: 'texto' as const,
        x: 196,
        y: 210,
        largura: 440,
        altura: 41,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{ministro_nome}',
      },
      {
        id: '161d7f6b-1f34-42ed-8508-3a48ffd84cd6',
        tipo: 'texto' as const,
        x: 209,
        y: 512,
        largura: 205,
        altura: 23,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '1777052623192saa853y',
        tipo: 'texto' as const,
        x: 426,
        y: 511,
        largura: 205,
        altura: 23,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{data_consagracao}',
      },
    ],
  },
  {
    id: 'ministerial-missionario-padrao',
    nome: 'Consagração Missionário(a)',
    chave: 'ministerial-missionario-padrao',
    categoria: 'ministerial' as const,
    ativo: true,
    backgroundUrl: undefined as any,
    elementos: [
      {
        id: 'b9268db5-9e61-48fc-ae7e-9f016afb0e23',
        tipo: 'logo' as const,
        x: 37,
        y: 232,
        largura: 118,
        altura: 132,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: '081d551b-d679-4a88-bc34-f931f67b43c8',
        tipo: 'texto' as const,
        x: 183,
        y: 213,
        largura: 471,
        altura: 40,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{ministro_nome}',
      },
      {
        id: 'cb4a1e1b-25aa-43e6-98c1-0945fc43216c',
        tipo: 'texto' as const,
        x: 197,
        y: 514,
        largura: 217,
        altura: 20,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '1777051489877hrt0a3x',
        tipo: 'texto' as const,
        x: 425,
        y: 514,
        largura: 206,
        altura: 20,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{data_consagracao}',
      },
    ],
  },
  {
    id: 'ministerial-presbitero-padrao',
    nome: 'Consagração Presbítero',
    chave: 'ministerial-presbitero-padrao',
    categoria: 'ministerial' as const,
    ativo: true,
    backgroundUrl: undefined as any,
    elementos: [
      {
        id: 'e5390d5e-9d43-4ea4-9aa5-25cae1ea19cb',
        tipo: 'logo' as const,
        x: 42,
        y: 304,
        largura: 105,
        altura: 138,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: 'f7090f99-d1e3-43a6-b5c0-4b1a477c00a7',
        tipo: 'texto' as const,
        x: 186,
        y: 221,
        largura: 465,
        altura: 39,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{ministro_nome}',
      },
      {
        id: '564c9a70-af30-4100-8524-2b6e0f0ff8c4',
        tipo: 'texto' as const,
        x: 219,
        y: 500,
        largura: 193,
        altura: 20,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '1777050303702z30i3ox',
        tipo: 'texto' as const,
        x: 432,
        y: 499,
        largura: 193,
        altura: 20,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{data_consagracao}',
      },
    ],
  },
  {
    id: 'ministerial-diaconiza-padrao',
    nome: 'Consagração Diaconisa',
    chave: 'ministerial-diaconiza-padrao',
    categoria: 'ministerial' as const,
    ativo: true,
    backgroundUrl: undefined as any,
    elementos: [
      {
        id: 'f06e1232-1ebb-45a5-9a95-969b79f72915',
        tipo: 'logo' as const,
        x: 115,
        y: 192,
        largura: 99,
        altura: 125,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: '9875d06a-3d97-44d1-b673-bf6890e0c4e2',
        tipo: 'texto' as const,
        x: 200,
        y: 218,
        largura: 456,
        altura: 39,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{ministro_nome}',
      },
      {
        id: '9a743a50-48f1-45de-aeec-14acbb9759fd',
        tipo: 'texto' as const,
        x: 206,
        y: 479,
        largura: 212,
        altura: 24,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Arial',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '1777048014058ql55s0s',
        tipo: 'texto' as const,
        x: 422,
        y: 479,
        largura: 212,
        altura: 24,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Arial',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{data_consagracao}',
      },
    ],
  },
  {
    id: 'consagracao-obreiro-padrao',
    nome: 'Consagração de Obreiro',
    chave: 'consagracao-obreiro-padrao',
    categoria: 'consagracao-obreiro' as const,
    ativo: true,
    backgroundUrl: '/img/cert_diacono.jpg',
    elementos: [
      {
        id: '5b961f06-7202-4df3-8874-11194f198a4c',
        tipo: 'logo' as const,
        x: 57,
        y: 228,
        largura: 114,
        altura: 151,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: '1ef3b217-5578-49b8-9700-76ead5167bf7',
        tipo: 'texto' as const,
        x: 179,
        y: 223,
        largura: 482,
        altura: 42,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{obreiro_nome}',
      },
      {
        id: 'f575e61b-8a5a-455a-b7c0-04981221e918',
        tipo: 'texto' as const,
        x: 198,
        y: 515,
        largura: 220,
        altura: 22,
        fontSize: 11,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'right' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '1777045799219teof90k',
        tipo: 'texto' as const,
        x: 424,
        y: 516,
        largura: 173,
        altura: 20,
        fontSize: 11,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'left' as const,
        visivel: true,
        texto: '{data_consagracao}',
      },
    ],
  },
  {
    id: 'ebd-padrao',
    nome: 'EBD — Escola Bíblica Dominical',
    chave: 'ebd-padrao',
    categoria: 'ebd' as const,
    ativo: true,
    backgroundUrl: '/img/cert_ebd.jpg',
    elementos: [
      {
        id: 'c3350cb1-3b15-4d04-9bf9-f75191d6bdfc',
        tipo: 'logo' as const,
        x: 18,
        y: 437,
        largura: 122,
        altura: 136,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: 'c7797452-2144-4ee9-8367-060a0c19f3ad',
        tipo: 'texto' as const,
        x: 166,
        y: 196,
        largura: 506,
        altura: 40,
        fontSize: 18,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{aluno_nome}',
      },
      {
        id: '1777072968352wmafea0',
        tipo: 'texto' as const,
        x: 525,
        y: 234,
        largura: 176,
        altura: 23,
        fontSize: 11,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'left' as const,
        visivel: true,
        negrito: true,
        texto: '{trimestre}',
      },
      {
        id: 'a479e2d6-e362-47f6-b4bc-8633e73ab750',
        tipo: 'texto' as const,
        x: 156,
        y: 416,
        largura: 143,
        altura: 23,
        fontSize: 10,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{classe_nome}',
      },
      {
        id: '1777044872386qei28pw',
        tipo: 'texto' as const,
        x: 307,
        y: 416,
        largura: 217,
        altura: 23,
        fontSize: 10,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '1777044891438prw3a1p',
        tipo: 'texto' as const,
        x: 528,
        y: 415,
        largura: 154,
        altura: 25,
        fontSize: 10,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{data_emissao}',
      },
    ],
  },
  {
    id: 'batismo-aguas-padrao',
    nome: 'Batismo nas Águas',
    chave: 'batismo-aguas-padrao',
    categoria: 'batismo-aguas' as const,
    ativo: true,
    backgroundUrl: undefined as any,
    elementos: [
      {
        id: '921cf954-f87e-49ae-914d-b8c3f574e56a',
        tipo: 'texto' as const,
        x: 163,
        y: 192,
        largura: 507,
        altura: 51,
        fontSize: 22,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{candidato_nome}',
        negrito: false,
      },
      {
        id: '522dfa0d-dc57-4ab9-850f-9b8b6725210c',
        tipo: 'texto' as const,
        x: 191,
        y: 433,
        largura: 148,
        altura: 26,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{data_batismo}',
      },
      {
        id: '17770396541354ijgnlo',
        tipo: 'texto' as const,
        x: 344,
        y: 433,
        largura: 141,
        altura: 27,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{local_batismo}',
      },
      {
        id: '1777039745949rhsshhx',
        tipo: 'texto' as const,
        x: 489,
        y: 433,
        largura: 177,
        altura: 27,
        fontSize: 12,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{nome_igreja}',
      },
      {
        id: '5e1f2800-3fa0-42d1-84c7-76409776df3d',
        tipo: 'logo' as const,
        x: 24,
        y: 453,
        largura: 109,
        altura: 114,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
    ],
  },
  {
    id: 'casamento-padrao',
    nome: 'Casamento',
    chave: 'casamento-padrao',
    categoria: 'casamento' as const,
    ativo: true,
    backgroundUrl: undefined as any,
    elementos: [
      {
        id: '9234a664-4f9a-4c7d-9ddd-490c0dbb4a76',
        tipo: 'texto' as const,
        x: 170,
        y: 186,
        largura: 501,
        altura: 45,
        fontSize: 17,
        cor: '#804000',
        fonte: 'Comic Sans MS',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{conjuge1_nome} & {conjuge2_nome}',
      },
      {
        id: 'c97c56fa-c19e-4661-83d1-9c4adadac07a',
        tipo: 'logo' as const,
        x: 27,
        y: 250,
        largura: 118,
        altura: 143,
        fontSize: 16,
        cor: '#111827',
        fonte: 'Arial',
        alinhamento: 'left' as const,
        visivel: true,
      },
      {
        id: '68da61f0-7617-4b4f-a6af-908c6d3305fc',
        tipo: 'texto' as const,
        x: 173,
        y: 435,
        largura: 125,
        altura: 24,
        fontSize: 16,
        cor: '#804000',
        fonte: 'Arial',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{data_casamento}',
      },
      {
        id: '1777042538568yzp8hio',
        tipo: 'texto' as const,
        x: 303,
        y: 436,
        largura: 224,
        altura: 25,
        fontSize: 16,
        cor: '#804000',
        fonte: 'Arial',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{pastor_nome}',
      },
      {
        id: '1777042568503977ruyb',
        tipo: 'texto' as const,
        x: 533,
        y: 436,
        largura: 151,
        altura: 27,
        fontSize: 16,
        cor: '#804000',
        fonte: 'Arial',
        alinhamento: 'center' as const,
        visivel: true,
        texto: '{local_casamento}',
      },
    ],
  },
  {
    id: 'apresentacao-criancas-padrao',
    nome: 'Apresentação de Crianças',
    chave: 'apresentacao-criancas-padrao',
    categoria: 'apresentacao-criancas' as const,
    ativo: true,
    backgroundUrl: '/img/cert_apcrianca.png',
    elementos: [
      {
        x: 135,
        y: 238,
        id: 'aeda01e2-838d-4d69-9f7c-9195b42d765a',
        cor: '#004080',
        tipo: 'texto' as const,
        fonte: 'Comic Sans MS',
        texto: '{crianca_nome}',
        altura: 40,
        largura: 546,
        visivel: true,
        fontSize: 18,
        alinhamento: 'center' as const,
      },
      {
        x: 206,
        y: 310,
        id: '17762201527499ywqz9y',
        cor: '#004080',
        tipo: 'texto' as const,
        fonte: 'Comic Sans MS',
        texto: 'DATA: {data_apresentacao}',
        altura: 29,
        locked: false,
        largura: 376,
        negrito: true,
        visivel: true,
        fontSize: 14,
        alinhamento: 'center' as const,
      },
      {
        x: 225,
        y: 356,
        id: '1776220095713x4h0m30',
        cor: '#004080',
        tipo: 'texto' as const,
        fonte: 'Comic Sans MS',
        texto: '{pai_nome}',
        altura: 29,
        locked: false,
        largura: 376,
        visivel: true,
        fontSize: 14,
        alinhamento: 'center' as const,
      },
      {
        x: 227,
        y: 387,
        id: '1776220114545jlxw06y',
        cor: '#004080',
        tipo: 'texto' as const,
        fonte: 'Comic Sans MS',
        texto: '{mae_nome}',
        altura: 29,
        locked: false,
        largura: 376,
        visivel: true,
        fontSize: 14,
        alinhamento: 'center' as const,
      },
      {
        x: 55,
        y: 412,
        id: '0d12479c-c9b0-4adf-8f0c-d293dfabc67b',
        cor: '#111827',
        tipo: 'logo' as const,
        fonte: 'Arial',
        altura: 134,
        largura: 115,
        visivel: true,
        fontSize: 16,
        alinhamento: 'left' as const,
      },
      {
        x: 257,
        y: 521,
        id: '5956da07-5f2c-4019-8a14-01bdfe27ac0e',
        cor: '#004080',
        tipo: 'texto' as const,
        fonte: 'Comic Sans MS',
        texto: '{nome_igreja}',
        altura: 40,
        largura: 320,
        negrito: true,
        visivel: true,
        fontSize: 12,
        alinhamento: 'center' as const,
      },
    ],
  },
];
